# This is a basic workflow to help you get started with Actions

name: GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Fetch Hugo themes (true OR recursive)
          submodules: true  
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0    

      # Runs a single command using the runners shell
      - name: Hugo setup
      # You may pin to the exact commit or the version.
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          hugo-version: 'latest'
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true

      - name: Build
        run: hugo --minify

      # Runs a set of commands using the runners shell
      - name: Deploy
        # You may pin to the exact commit or the version.
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
